#Generated by Fabric Compiler ( version 2019.1-patch11 <build 44256> ) at Sat Oct 26 22:28:02 2019

project -load "C:/Users/zzl/Desktop/FPGA/PANGO/my_video_v2.1/synthesize/synplify_impl/../synplify_pro.prj"
open_file "C:/Users/zzl/Desktop/FPGA/PANGO/my_video_v2.1/synthesize/synplify_impl/synplify.srs"
