// Generated by IP Generator (Version 2019.1-patch11 build 44256)
// Module Instantiation Template
// Insert the following codes into your Verilog file.
//   * Change <InstanceName> to your own instance name.
//   * Fill in your own signal names in the port connections.

fifo_22i_22o <InstanceName> (
    .clk(),
    .rst(),
    .wr_en(),
    .wr_data(),
    .wr_full(),
    .almost_full(),
    .rd_en(),
    .rd_data(),
    .rd_empty(),
    .almost_empty());
