#Generated by Fabric Compiler ( version 2019.1-patch11 <build 44256> ) at Wed Oct 23 13:08:09 2019

add_constraint -logic -fdc "C:/Users/zzl/Desktop/FPGA/PANGO/my_video_v1.3/ipcore/ddr3/pnr/ctrl_phy_22/ddr_256_left.fdc"
add_constraint -logic -fdc "C:/Users/zzl/Desktop/FPGA/PANGO/my_video_v1.3/ipcore/ddr3/pnr/ctrl_phy_22/ddr_324_left.fdc"
set_arch -family Logos -device PGL22G -speedgrade -7 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -7 -package BG324
synthesize -synplify_pro 
dev_map 
pnr 
report_timing 
gen_bit_stream 
