// Generated by IP Generator (Version 2019.1-patch11 build 44256)
// Module Instantiation Template
// Insert the following codes into your Verilog file.
//   * Change <InstanceName> to your own instance name.
//   * Fill in your own signal names in the port connections.

APM_multi_add_s16 <InstanceName> (
    .a0(),
    .a1(),
    .b0(),
    .b1(),
    .clk(),
    .rst(),
    .ce(),
    .addsub(),
    .p());
